name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - develop


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "sfsdf"
        shell: bash
        run: echo "HELLO"

